# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  asana_secret: 
    description: 'Personal Access Token'
    required: true
  pr_name: 
    description: 'name of the PR'
    required: true
  pr_merge: 
    description: 'is the PR merged'
    required: true
  pr_nb_for_deploy: 
    description: 'pr nb for deploy'
    required: false
  repo_name: 
    description: 'repo name'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ASANA_ACCESS_TOKEN: ${{ inputs.asana_secret }}
    PR_NAME: ${{ inputs.pr_name }}
    PR_MERGE: ${{ inputs.pr_merge }}
    PR_NB_FOR_DEPLOY: ${{ inputs.pr_nb_for_deploy }}
    REPO_NAME: ${{ inputs.repo_name}}
