# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  asana_secret: 
    description: 'Personal Access Token'
    required: true
  pr_name: 
    description: 'name of the PR'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ASANA_ACCESS_TOKEN: ${{ inputs.asana_secret }}
    PR_NAME: ${{ inputs.pr_name }}