on: 
  pull_request:
      types: [closed]
      branches: 
        - production

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps: 
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          asana_secret: ${{ secrets.ASANA_ACCESS_TOKEN }}
          pr_merge: ${{github.event.pull_request.merged == true}}
          pr_nb_for_deploy: ${{github.event.pull_request.number}}
          repo_name: ${{github.event.repository.name}}
      - name: Get the number of PR
        id: name
        run: echo "The name of the PR is ${{ github.event.pull_request.number}} "
